[package]
name = "bevy_framepace"
version = "0.10.0"
edition = "2021"
resolver = "2"
description = "Frame pacing and frame limiting for Bevy"
license = "MIT OR Apache-2.0"
repository = "https://github.com/aevyrie/bevy_framepace"
documentation = "https://docs.rs/bevy_framepace"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.9", default-features = false, features = [
    "bevy_render",
    "bevy_winit",
] }
spin_sleep = "1.0"

[features]
default = ["debug", "bevy/x11"]
debug = ["bevy/bevy_sprite", "bevy/bevy_core_pipeline", "bevy/bevy_asset"]

[dev-dependencies]
bevy = { version = "0.9.1", default-features = false, features = [
    "bevy_asset",
    "bevy_core_pipeline",
    "bevy_sprite",
    "bevy_text",
    "bevy_ui",
    "bevy_winit",
] }
